config/routes.rb
Rails.application.routes.draw do
  root "library#welcome"
  get "checkin" => "library#new_checkin"
  post "checkin" => "library#checkin"
  get "checkout" => "library#new_checkout"
  post "checkout" => "library#checkout"

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :patron
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  belongs_to :patron
  belongs_to :book

  def checked_out
    if checkin_at.nil?
    end
  end

end

app/models/patron.rb
class Patron < ActiveRecord::Base
  has_many :books, through: :checkouts
  has_many :checkouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController

def library_books
  @books = Book.all
  @patrons = Patron.all
end

def checkin
  @checkout = Checkout.find(params[:checkout_id])
  if @checkout.book.update(available: true)
    redirect_to root, notice: "Thanks for Checking in #{@books}"
  else
    render :new_checkin
  end
end

def new_checkin
  @checkout = Checkout.where("checkin_done is null")
end

  def new_checkout
  @checkout = Checkout.new
  if params[:book_id]
    @checkout.book  = Book.find(params[:book_id])
  end
end

def checkout
  @checkout = Checkout.new(params.require(:checkout).permit(:book_id, :patron_id))
  if @checkout.save
    @checkout.book.available = false
    @checkout.book.save
  end
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/library/checkin_html.erb
<h1>library CheckIn's</h1>



<h2>Have a book to checkin?<h2>
  <% @checkouts.each do |checkout| %>
  <%= checkout.title "Checked out by" patron.name %>
  <% end %>
  <%= link_to "Checkin", checkin_path(checkout_id: checkout.id) %>

app/views/library/checkout.html.erb
<h1> CheckOut A Book! </h1>

<%= form_for @checkout, url:checkout_path do |c| %>
    <%= f.label :book %>
    <%= f.collection_select :book_id, Book.all, :id, :title, prompt: true %>

    <%= f.label :patron %>
    <%= f.collection_select :patron_id, Patron.all, :id, :name, prompt: true %>

    <%= f.submit "I want to checkout this book" %>

<% end %>

app/views/library/welcome.html.erb
<h1>Welcome! This is the Library</h1>


<h2>Books that we have in our library</h2>

<% @books.each do |book| %>
    <%= book.title %>
    <% if book.available? %>
      <%= link_to "Checkout", checkout_path(book_id: book.id) %>
    <% end %>

<% end %>